### PR TITLE
CORE-13382: scan only runntime classpath 

### PR DESCRIPTION
**Pull request by ronanbrowne**
Updated snyk configuration to scan only shippable code in line with other repos.  Not items which are internal to the build system plugins etc

### CODE REVIEW

**Comment by r3tc** [comment]
Jenkins build for PR 167 build 1

Build Successful:
Jar artifact version produced by this PR: 5.0.0-alpha-1684964806973

**Review by driessamyn — APPROVED** [review]
LGTM

**Review by wzur-r3 — APPROVED** [review]
LGTM

**Comment by r3tc** [comment]
Jenkins build for PR 167 build 2

Build Successful:
Jar artifact version produced by this PR: 5.0.0-alpha-1685007205136

**Review by mnesbit — APPROVED** [review]
OK

**Pull request merged**
