### PR TITLE
ES-91: Upgrade Gradle Version

### PR DESCRIPTION
**Pull request by knguyen-r3**
* Upgrade gradle version to 8.1 and create new gradle wrapper as part of C5 update.
* Added new files that were modified when running gradle with new version
* Update check-pr-title.yml workflow to be able to accept ES PR

### CODE REVIEW

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Comment by ronanbrowne** [comment]
@knguyen-r3 lets hold off merging these until Beta3 is shipped (this coming week), Everything should be fine but I don't want to risk any last-minute surprises on release jobs.

**Review by yarivus — COMMENTED** [review]
LGTM (except for the commenting out of the gradlew.bat) - checkpointing review

**Comment by ronanbrowne** [comment]
> LGTM (except for the commenting out of the gradlew.bat) - checkpointing review

FYI changes in gradlew.bat and gradlew are generated by gradle once you update the wrapper and run a local gradle command the new supporting files are auto-generated and need to be committed like so

**Review by yarivus — APPROVED** [review]
LGTM

**Pull request merged**
